openapi: 3.0.0
info:
  title: Url Shortener API
  version: 0.1.0
paths:
  /api/url/shorten:
    post:
      summary: Url shortener
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      shortened_url:
                        type: string
        '400':
          description: Bad Request
      operationId: url-shortener
      description: Given any provided url returns shortened one
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri